# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5a71b64224375cf0646375382fc73edea9d10732c208ce8df2d8419566e298f3e2f239fb33c302dd40d0d8edaf332346dfeadb7a443cae2b573dc940cf152368

test:
  secret_key_base: d79240348f271cb0214b509823831a96ce1242ef525970b873b2445223dcc9ba64cb9ebdd0ae941951ad9eb1914f0efa0754cd9ad2817682050cba77ad5d4c41

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
